### ISSUE TITLE
Can't start twitch-master

### ISSUE THREAD

**Issue by computernewb** [twitchinstallsarchlinux/twitch-master#13]
darren@home:~/twitch-master-master$ ./init.sh twitch_master

fs.js:436
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'config.json'
    at Object.fs.openSync (fs.js:436:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.<anonymous> (/home/darren/twitch-master-master/twitch_master.js:79:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

It needs a file called config.json. But there is no config.json included. Where do I find the config.json or how do I generate it?

**Comment by deelowe** [comment]
The config is sparsely used. It only contains the info needed for connecting with twitch (username and pass)


Here's the relevant bits:

https://github.com/twitchinstallsarchlinux/twitch-master/blob/master/twitch_master.js#L44-L51

```javascript
// Load json config
var config = JSON.parse(fs.readFileSync('config.json', 'utf8'));

var twitch_chat = new irc.Client('irc.twitch.tv', config['nick'], {
    channels: ['#' + config['nick']],
    userName: config['nick'],
    password: config['password'],
    autoConnect: false
});
```
